package main

import (
	"fmt"

	"github.com/pion/interceptor"
	"github.com/pion/interceptor/pkg/intervalpli"
	"github.com/pion/webrtc/v4"
)

func handleWebRTCOffer(offer webrtc.SessionDescription, room *Room, peer *Peer) (*webrtc.SessionDescription, error) {
	// Create a MediaEngine object to configure the supported codec
	mediaEngine := &webrtc.MediaEngine{}

	if err := mediaEngine.RegisterCodec(webrtc.RTPCodecParameters{
		RTPCodecCapability: webrtc.RTPCodecCapability{
			MimeType:  webrtc.MimeTypeOpus,
			ClockRate: 48000,
			Channels:  2,
		},
		PayloadType: 111,
	}, webrtc.RTPCodecTypeAudio); err != nil {
		return nil, fmt.Errorf("failed to register codec: %w", err)
	}

	// Create a InterceptorRegistry. This is the user configurable RTP/RTCP Pipeline.
	// This provides NACKs, RTCP Reports and other features. If you use `webrtc.NewPeerConnection`
	// this is enabled by default. If you are manually managing You MUST create a InterceptorRegistry
	// for each PeerConnection.
	interceptorRegistry := &interceptor.Registry{}

	// Use the default set of Interceptors
	if err := webrtc.RegisterDefaultInterceptors(mediaEngine, interceptorRegistry); err != nil {
		panic(err)
	}

	// Register a intervalpli factory
	// This interceptor sends a PLI every 3 seconds. A PLI causes a video keyframe to be generated by the sender.
	// This makes our video seekable and more error resilent, but at a cost of lower picture quality and higher bitrates
	// A real world application should process incoming RTCP packets from viewers and forward them to senders
	intervalPliFactory, err := intervalpli.NewReceiverInterceptor()
	if err != nil {
		panic(err)
	}
	interceptorRegistry.Add(intervalPliFactory)

	// Create the API object with the MediaEngine
	api := webrtc.NewAPI(webrtc.WithMediaEngine(mediaEngine), webrtc.WithInterceptorRegistry(interceptorRegistry))

	// Prepare the configuration
	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}
	// Create a new RTCPeerConnection
	peerConnection, err := api.NewPeerConnection(config)
	if err != nil {
		panic(err)
	}

	peer.pc = peerConnection

	// Add all existing peers' tracks to this new peer's connection before answering
	room.mu.RLock()
	for _, localTrack := range room.localTracks {
		sender, err := peerConnection.AddTrack(localTrack)
		if err != nil {
			room.mu.RUnlock()
			return nil, fmt.Errorf("failed to add existing track: %w", err)
		}
		go drainRTCP(sender)
	}
	room.mu.RUnlock()

	room.AddPeer(peer)

	// Set a handler for when a new remote track starts; forward it to all other peers
	peerConnection.OnTrack(func(track *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) { //nolint: revive
		fmt.Printf("Track has started, of type %d: %s \n", track.PayloadType(), track.Codec().MimeType)

		localTrack, err := webrtc.NewTrackLocalStaticRTP(track.Codec().RTPCodecCapability, track.ID(), track.StreamID())
		if err != nil {
			return
		}

		room.mu.Lock()
		room.localTracks[peer.id] = localTrack
		room.mu.Unlock()

		for otherID, otherPeer := range room.GetPeers() {
			if otherID == peer.id {
				continue
			}
			sender, err := otherPeer.pc.AddTrack(localTrack)
			if err != nil {
				continue
			}
			go drainRTCP(sender)
			go renegotiate(otherPeer)
		}

		for {
			rtp, _, readErr := track.ReadRTP()
			if readErr != nil {
				return
			}
			if writeErr := localTrack.WriteRTP(rtp); writeErr != nil {
				return
			}
		}
	})

	// Set the handler for Peer connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnConnectionStateChange(func(state webrtc.PeerConnectionState) {
		fmt.Printf("Peer Connection State has changed: %s\n", state.String())

		if state == webrtc.PeerConnectionStateFailed {
			// Wait until PeerConnection has had no network activity for 30 seconds or another failure.
			// It may be reconnected using an ICE Restart.
			// Use webrtc.PeerConnectionStateDisconnected if you are interested in detecting faster timeout.
			// Note that the PeerConnection may come back from PeerConnectionStateDisconnected.
			fmt.Println("Peer Connection has gone to failed exiting")
			peerConnection.Close()
			room.RemovePeer(peer.id)
		}

		if state == webrtc.PeerConnectionStateClosed {
			// PeerConnection was explicitly closed. This usually happens from a DTLS CloseNotify
			fmt.Println("Peer Connection has gone to closed exiting")
			room.RemovePeer(peer.id)
		}
	})

	if err = peerConnection.SetRemoteDescription(offer); err != nil {
		panic(err)
	}

	// Create an answer
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}

	// Create channel that is blocked until ICE Gathering is complete
	gatherComplete := webrtc.GatheringCompletePromise(peerConnection)

	// Sets the LocalDescription, and starts our UDP listeners
	if err = peerConnection.SetLocalDescription(answer); err != nil {
		panic(err)
	}

	// Block until ICE Gathering is complete, disabling trickle ICE
	// we do this because we only can exchange one signaling message
	// in a production application you should exchange ICE Candidates via OnICECandidate
	<-gatherComplete

	return peerConnection.LocalDescription(), nil
}

func drainRTCP(sender *webrtc.RTPSender) {
	rtcpBuf := make([]byte, 1500)
	for {
		if _, _, err := sender.Read(rtcpBuf); err != nil {
			return
		}
	}
}

func renegotiate(peer *Peer) {
	offer, err := peer.pc.CreateOffer(nil)
	if err != nil {
		return
	}

	gatherComplete := webrtc.GatheringCompletePromise(peer.pc)

	if err = peer.pc.SetLocalDescription(offer); err != nil {
		return
	}

	<-gatherComplete

	if err = peer.SendSDP(*peer.pc.LocalDescription()); err != nil {
		return
	}

	answer := <-peer.answerCh

	peer.pc.SetRemoteDescription(answer) //nolint: errcheck
}
