// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListAudioDevices() {
    return window['go']['main']['App']['ListAudioDevices']();
}

export function ListRooms(arg1) {
    return window['go']['main']['App']['ListRooms'](arg1);
}

export function CreateRoom(arg1, arg2) {
    return window['go']['main']['App']['CreateRoom'](arg1, arg2);
}

export function JoinRoom(arg1, arg2, arg3) {
    return window['go']['main']['App']['JoinRoom'](arg1, arg2, arg3);
}

export function LeaveRoom() {
    return window['go']['main']['App']['LeaveRoom']();
}

export function SessionStatus() {
    return window['go']['main']['App']['SessionStatus']();
}
