// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AudioDeviceInfo {
    name: string;
}

export interface AudioDevices {
    capture: AudioDeviceInfo[];
    playback: AudioDeviceInfo[];
}

export interface RoomInfo {
    id: string;
    name: string;
}

export function ListAudioDevices(): Promise<AudioDevices>;
export function ListRooms(serverURL: string): Promise<RoomInfo[]>;
export function CreateRoom(serverURL: string, name: string): Promise<RoomInfo>;
export function JoinRoom(wsURL: string, captureIndex: number, playbackIndex: number): Promise<void>;
export function LeaveRoom(): Promise<void>;
export function SessionStatus(): Promise<string>;
